apiVersion: v1
kind: Pod
metadata:
  name: kubewatch
  namespace: default
spec:
  containers:
  - name: kubewatch
    image: bitnami/kubewatch
    imagePullPolicy: Always    
    volumeMounts:
    - name: config-volume
      mountPath: /opt/bitnami/kubewatch/.kubewatch.yaml
      subPath: .kubewatch.yaml
  - name: proxy
    image: bitnami/kubectl
    args:
      - proxy
      - "-p"
      - "8080"
    imagePullPolicy: Always
  restartPolicy: Always
  volumes:
  - name: config-volume
    configMap:
      name: kubewatch
